Add Hardware Replacement Tracker
nautobot/nautobot-app-device-lifecycle-mgmt pull request #206
Opened 2023-08-14 22:28 UTC by sdoiron0330

Add a new model to track Hardware Replacements as a part of a device's lifecycle.

As a device reaches the end of its lifecycle, it would be nice to have a list of the recommended replacement hardware types as information readily available for a device.

![image](https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/assets/53412380/afc4dc2d-6431-4675-a428-e2f7bbf44271)

![image](https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/assets/53412380/68065637-73c6-4863-8b48-3dc578cb74d4)

![image](https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/assets/53412380/ec954241-f89a-48a4-8520-c46414dfb42d)

![image](https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/assets/53412380/eec77fbb-501d-4b03-8405-3c5a5a64c1c7)

2023-08-18 12:32 UTC, progala requested changes
A great addition to the plugin, thanks @sdoiron0330 . I have just a few comments and suggestions.

- Please add docs explaining how to use this functionality.
- Update nav group name to "Hardware Lifecycle" from "Hardware Notices"
- Let's move template for device page to its own inc template. This should simplify the logic and make it easier to maintain.
- Do you also want to display matching hardware replacements on the Device Type page?

2023-08-18 12:32 UTC, progala commented on nautobot_device_lifecycle_mgmt/models.py
> +        related_name="replacement_inventory_item",
Perhaps `inventory_item_replacement_for` .

2023-08-18 12:32 UTC, progala commented on nautobot_device_lifecycle_mgmt/templates/nautobot_device_lifecycle_mgmt/inc/device_notice.html
> +            {% if replacements %}
This doesn't show up due to the below conditional at the top of the template:


```
{% if perms.nautobot_device_lifecycle_mgmt.view_hardwarelcm and 
hw_notices %}
```

In any case, I think we should move it to its own inc template.

2023-08-18 12:32 UTC, progala commented on nautobot_device_lifecycle_mgmt/template_content.py
> +                "replacements": HardwareReplacementLCM.objects.filter(current_device_type=dev_obj.device_type).filter(
```suggestion
                "hw_replacements": HardwareReplacementLCM.objects.filter(current_device_type=dev_obj.device_type).filter(
```

2023-08-18 12:32 UTC, progala commented on nautobot_device_lifecycle_mgmt/templates/nautobot_device_lifecycle_mgmt/inc/device_notice.html
> +            {% if replacements %}
```suggestion
            {% if hw_replacements %}
```

2023-08-18 12:32 UTC, progala commented on nautobot_device_lifecycle_mgmt/templates/nautobot_device_lifecycle_mgmt/inc/device_notice.html
> +                <a href="#replacements" aria-controls="hardware" role="tab" data-toggle="tab">
```suggestion
                <a href="#hw_replacements" aria-controls="hardware" role="tab" data-toggle="tab">
```

2023-08-18 12:32 UTC, progala commented on nautobot_device_lifecycle_mgmt/templates/nautobot_device_lifecycle_mgmt/inc/device_notice.html
> +                    Replacement Options <span class="badge badge-pill badge-primary">{{ replacements.count }}</span>
```suggestion
                    Replacement Options <span class="badge badge-pill badge-primary">{{ hw_replacements.count }}</span>
```

2023-08-18 12:32 UTC, progala commented on nautobot_device_lifecycle_mgmt/templates/nautobot_device_lifecycle_mgmt/inc/device_notice.html
> +            <div role="tabpanel" class="tab-pane" id="replacements">
```suggestion
            <div role="tabpanel" class="tab-pane" id="hw_replacements">
```

2023-08-18 12:32 UTC, progala commented on nautobot_device_lifecycle_mgmt/templates/nautobot_device_lifecycle_mgmt/inc/device_notice.html
> +                            {% for replacement in replacements %}
```suggestion
                            {% for replacement in hw_replacements %}
```

2023-08-21 21:08 UTC, bradh11 commented
@sdoiron0330  - Once you've addressed @progala 's suggestions we can target this for a 1.3.3 release and rebase into the next-2.0 branch.

2025-02-07 15:10 UTC, bradh11 commented
These capabilities will be targeted for refresh planner and future development outside of Device Lifecycle Management App

2025-02-07 15:10 UTC, closed without merging