Add custom contract types via plugin config
nautobot/nautobot-app-device-lifecycle-mgmt pull request #239
Opened 2023-10-18 16:15 UTC by qduk

This adds the ability to provide a list of contract types in your plugin configuration for use in the plugin. This is related to issue #103. I have a similar use case in my current work where `Hardware` and `Software` aren't specific enough and the use of a `services` and/or `software maintenance` are needed. Let me know what you guys think! Thanks!

2023-10-30 11:19 UTC, progala commented
Thanks @qduk, I like this idea. I'll have a look at this today and we should merge soon.

2023-10-30 21:49 UTC, progala commented
@qduk I noticed that these new contract types don't show up in the filter drop down menu.

2023-10-30 21:52 UTC, qduk commented
@progala hm let me look into it tomorrow and update here.

2023-10-31 14:13 UTC, bradh11 commented on development/nautobot_config.py
> +        "contract_types": ["Hardware Maintenance", "Subscription", "Software License", "Services", "Lease"],
Propose being more clear here that there are additional contract types that are appended to the defaults `Hardware` & `Software`

```suggestion
        "additional_contract_types": ["Hardware Maintenance", "Subscription", "Software License", "Services", "Lease"],
```

2023-10-31 14:15 UTC, bradh11 commented on nautobot_device_lifecycle_mgmt/utils.py
> +    defined_contract_types = PLUGIN_SETTINGS.get("contract_types", [])
```suggestion
    defined_additional_contract_types = PLUGIN_SETTINGS.get("additional_contract_types", [])
```

2023-10-31 14:15 UTC, bradh11 commented on nautobot_device_lifecycle_mgmt/utils.py
> +    return tuple((type, type) for type in defined_contract_types) + tuple(choices)
```suggestion
    return tuple((type, type) for type in defined_additional_contract_types) + tuple(choices)
```

2023-10-31 15:36 UTC, qduk commented
@progala Can you give it another shot? I was able to see the contract types in the dropdown. 
![Screenshot 2023-10-31 at 10 35 00 AM](https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/assets/38091261/0ac20a03-0d72-462b-b180-6c46433f5a88)

2023-10-31 15:36 UTC, qduk commented
@bradh11 Thanks for the suggestions. Do I need to open this toward a different branch? I saw the other one was closed.

2023-11-02 09:43 UTC, progala commented
> @bradh11 Thanks for the suggestions. Do I need to open this toward a different branch? I saw the other one was closed.

The other PR was closed as it was targeting `develop`. We tried to retarget it for ltm1.6 but diff was showing too many unrelated changes. Can you try branching off ltm1.6 and reapplying your changes?

2023-11-03 14:15 UTC, bradh11 approved these changes

2024-01-09 14:55 UTC, progala requested changes
Small suggestion. Could you please also add tests for `add_custom_contract_types`

2024-01-09 14:55 UTC, progala commented on nautobot_device_lifecycle_mgmt/utils.py
> +    return tuple((type, type) for type in defined_additional_contract_types) + tuple(choices)
```suggestion
    return tuple((contract_type, contract_type) for contract_type in defined_additional_contract_types) + tuple(choices)
```

2024-01-09 14:55 UTC, progala commented on development/nautobot_config.py
> +        "additional_contract_types": ["Hardware Maintenance", "Subscription", "Software License", "Services", "Lease"],
```suggestion
        "additional_contract_types": os.environ.get(
            "DEVICE_LIFECYCLE_ADD_CONTRACT_TYPES",
            "Hardware Maintenance,Subscription,Software License,Services,Lease",
        ).split(","),
```

2024-01-11 15:37 UTC, qduk commented
@progala Test added here as well. Let me know if these suffice. Thanks!

2024-01-12 16:34 UTC, merged